<CalcButton@Button>:
    font_size: 18
<Calculadora>:
    orientation:"vertical"
    padding: 15
    spacing: 15
        
    Label:
        text: root.display
        color: root.rstd_c
        font_size:40
        bold: True
        padding: [20, 10]
        halign: "right"
        valign: "middle"
        text_size: self.size

        shorten: True
        shorten_from: "left"

        canvas.before:
            Color:
                rgba: 1, 1, 1, 0.2
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [20]
    GridLayout:
        id: grid_btn
        cols: 4
        spacing: 10
        size_hint_y: 3